sudo: required
services:
  - docker

script:
  - docker build -t noneuser2183/webcomplexawsc ./client
  - docker build -t noneuser2183/webcomplexawsn ./nginx
  - docker build -t noneuser2183/webcomplexawss ./server
  - docker build -t noneuser2183/webcomplexawsw ./worker
  - echo "$docpass" | docker login -u "$docid" --password-stdin
  - docker push noneuser2183/webcomplexawsc 
  - docker push noneuser2183/webcomplexawsn
  - docker push noneuser2183/webcomplexawss
  - docker push noneuser2183/webcomplexawsw